services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    container_name: mt-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    container_name: mt-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - NEXT_PUBLIC_API_HOST=http://localhost:8080/api/v1
    container_name: mt-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend